# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dan Taylor
tagline:          no witty tagline
url:              http://dantaylor688.github.io
paginate:         1
baseurl:          http://dantaylor688.github.io/
author:
  name:           Dan Taylor
  url:            https://twitter.com/dantaylor688
  email:          dantaylor688@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dantaylor688.github.io
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# MathJax  
markdown: kramdown
