# Permalinks
permalink:        pretty

# Setup
title:            Dan Taylor
tagline:          Math. Data Science. Exposition.
url:              http://dantaylor688.github.io
paginate:         1
baseurl:          http://dantaylor688.github.io/
author:
  name:           Dan Taylor
  url:            https://twitter.com/dantaylor688
  email:          dantaylor688@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dantaylor688.github.io

collections:
   sunday-school-lessons:
       output: true

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  Misc: '/misc'
  Sunday School: '/sunday-school'

# MathJax
markdown: kramdown
